volumes:
  chroma_data:
  node_modules:

services:
  worker:
    build:
      context: ../
      dockerfile: .deploy/Dockerfile
    depends_on:
      - chroma
    volumes:
      - ../:/opt/app
      - node_modules:/opt/app/node_modules
    command: ['npm', 'start']
